- docs/sphinx/target-selection.rst
- python/target_selection/__init__.py
- python/target_selection/__main__.py
- python/target_selection/cartons/base.py
- python/target_selection/cartons/guide.py
- python/target_selection/config/target_selection.yml
- setup.cfg
Allows to define a region to limit the carton query. Removes tiling options that are no longer working.
> Query region

- python/target_selection/cartons/base.py
- python/target_selection/cartons/ops_skies.py
- python/target_selection/config/target_selection.yml
- ops_boss_sky
- ops_apogee_sky
Also introduces new `BaseCarton.load_magnitudes` to skip magnitude loading into `targetdb.magnitude`.
> Skies cartons

- python/target_selection/cartons/ops_apogee_stds.py
I have run the OPS_APOGEE_Stds_Carton and Kevin Covey has checked the output fits file.
> Ops apogee

- python/target_selection/cartons/mwm_yso.py
MWM_YSO_CMZ_APOGEE_Carton: add MIPSGAL.glon, MIPSGAL.glat to select statement
> MWM_YSO_CMZ_APOGEE_Carton: add MIPSGAL.glon, MIPSGAL.glat to select statement

- python/target_selection/cartons/mwm_cb.py
- python/target_selection/cartons/mwm_cb_uvex.py
- python/target_selection/cartons/mwm_dust.py
- python/target_selection/cartons/mwm_erosita.py
- python/target_selection/cartons/mwm_galactic.py
- python/target_selection/cartons/mwm_halo.py
- python/target_selection/cartons/mwm_legacy_ir2opt.py
- python/target_selection/cartons/mwm_ob.py
- python/target_selection/cartons/mwm_planet.py
- python/target_selection/cartons/mwm_rv.py
- python/target_selection/cartons/mwm_snc.py
- python/target_selection/cartons/mwm_tess_ob.py
- python/target_selection/cartons/mwm_tess_rgb.py
- python/target_selection/cartons/mwm_wd.py
- python/target_selection/cartons/mwm_yso.py
mwm cartons: set instrument and cadence
> mwm cartons: set instrument and cadence

- python/target_selection/cartons/mwm_rv.py
mwm_rv.py: MWM_RV_Long_Bplates_Carton:
add updated new field centers
add condition SDSS_APOGEE_AllStarMerge_r13.h < 12
> mwm_rv.py: add updated new field centers to MWM_RV_Long_Bplates_Carton

- python/target_selection/cartons/base.py
- python/target_selection/cartons/mwm_cb.py
- python/target_selection/cartons/mwm_rv.py
- python/target_selection/config/target_selection.yml
- setup.cfg
See [COS-44](https://jira.sdss.org/browse/COS-44)
> Update magnitude loading

- python/target_selection/cartons/bhm_rm.py
Allows future modifications to bhm_rm_tweaks table to be ignored by v0.5 targeting code
> bhm_rm_* cartons explicitly use specific date range from bhm_rm_tweaks

- python/target_selection/cartons/mwm_halo.py
removed low magnitude limit for MWM_Halo_Best_Brightest_BOSS_Carton and MWM_Halo_SkyMapper_BOSS_Carton : deleted cartons MWM_Halo_Best_Brightest_APOGEE_Carton and MWM_Halo_SkyMapper_APOGEE_Carton
> removed low magnitude limit for mwm_halo BOSS cartons

- python/target_selection/__main__.py
- python/target_selection/cartons/tools.py
- python/target_selection/config/target_selection.yml
__main__.py: give carton_name parameter to get_file_carton()
cartons/tools.py: add warnings
> open_fiber: __main__.py: give carton_name parameter to get_file_carton()

- python/target_selection/__main__.py
- python/target_selection/config/target_selection.yml
__main__.py: handle case where there are only open fiber cartons and no regular cartons
> __main__.py: handle case where there are only open fiber cartons

- CHANGELOG.md
- python/target_selection/__main__.py
- python/target_selection/cartons/base.py
Remove `sleep` instances in `base.py`. This should now work fine with `sdssdb/main`.
> Remove sleeps

- python/target_selection/cartons/ops_skies.py
- python/target_selection/config/target_selection.yml
Took version that included new BOSS cartons and added 2 apogee cartons ops_sky_apogee_best and ops_sky_apogee_good.
For the ops_sky_apogee_good carton I have hard coded a magnitude limit for the tmass neighbors which is 10 (at line 291).
But maybe at some point we want to put that in the configuration file like Tom did for the BOSS cartons.
> Updated new version of ops_skies.py

- CHANGELOG.md
- docs/sphinx/index.rst
- docs/sphinx/tagging.rst
- python/target_selection/__main__.py
- python/target_selection/cartons/base.py
- python/target_selection/cartons/bhm_galaxies.py
- python/target_selection/cartons/mwm_cb.py
- python/target_selection/cartons/mwm_erosita.py
- python/target_selection/cartons/mwm_halo.py
- python/target_selection/cartons/mwm_yso.py
- python/target_selection/cartons/ops_bright_stars.py
- python/target_selection/cartons/ops_skies.py
- python/target_selection/cartons/tools.py
- python/target_selection/config/target_selection.yml
- setup.cfg
To check conflicts and then update skies.py in skies_v05
> Merging main into skies_v05

- python/target_selection/cartons/tools.py
tools.py: get_file_carton(): check that category, program, and mapper values are valid
> tools.py: get_file_carton(): check category, program, mapper values.

- python/target_selection/cartons/ops_apogee_stds.py
Adding GAIA proper motion and Parallax cut to remove the cooler stars
> Updating ops_std_apogee carton

- python/target_selection/config/target_selection.yml
> Add missing config entry for bhm_spiders_agn_hard

- CHANGELOG.md
- python/target_selection/config/target_selection.yml
- setup.cfg
> Tag 1.0.29

- python/target_selection/cartons/mwm_cb.py
- python/target_selection/cartons/mwm_magcloud_rgb.py
- python/target_selection/config/target_selection.yml
- python/target_selection/exceptions.py
- setup.cfg
- mwm_magcloud_agb_apogee
- mwm_magcloud_rgb_boss
- mwm_cb_galex_vol
- mwm_cb_swiftuvot
- mwm_cb_xmmom
> Tag 1.0.32

- CHANGELOG.md
- README.md
- poetry.lock
- pyproject.toml
Modifies the `README.md` file with some instructions on how to handle parallel development with `sdssdb` and `target_selection`.
> Add instructions to tag and update sdssdb
